In [112]:
!{sys.executable} -m pip install tiktoken

ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

Collecting tiktoken
  Downloading tiktoken-0.7.0-cp38-cp38-win_amd64.whl (798 kB)
Collecting requests>=2.26.0
  Downloading requests-2.32.4-py3-none-any.whl (64 kB)
Collecting regex>=2022.1.18
  Downloading regex-2024.11.6-cp38-cp38-win_amd64.whl (274 kB)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.26.0->tiktoken) (2024.8.30)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.26.0->tiktoken) (2.10)
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.2-cp38-cp38-win_amd64.whl (105 kB)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests>=2.26.0->tiktoken) (1.25.11)
Installing collected packages: charset-normalizer, requests, regex, tiktoken
  Attempting uninstall: requests
    Found existing installation: requests 2.24.0
    Uninstalling requests-2.24.0:
      Successfully uninstalled requests-2.24.0
  Attempting uninstall: regex
    Found existing installation: regex 2020.10.15
    Uninstalling regex-2020.10.15:
      Successfully uninstalled regex-2020.10.15
Successfully installed charset-normalizer-3.4.2 regex-2024.11.6 requests-2.32.4 tiktoken-0.7.0

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

conda 4.12.0 requires ruamel_yaml_conda>=0.11.14, which is not installed.
google-api-core 2.10.0 requires protobuf<5.0.0dev,>=3.20.1, but you'll have protobuf 3.19.1 which is incompatible.

In [23]:
sys.executable

'C:\\ProgramData\\Anaconda3\\python.exe'

In [ ]:
!conda install -y pydantic

In [1]:
!pip install pydantic

Collecting pydantic
  Downloading pydantic-2.11.7-py3-none-any.whl.metadata (67 kB)
Collecting annotated-types>=0.6.0 (from pydantic)
  Downloading annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.33.2 (from pydantic)
  Downloading pydantic_core-2.33.2-cp39-cp39-win_amd64.whl.metadata (6.9 kB)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\monke\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pydantic) (4.14.1)
Collecting typing-inspection>=0.4.0 (from pydantic)
  Downloading typing_inspection-0.4.1-py3-none-any.whl.metadata (2.6 kB)
Downloading pydantic-2.11.7-py3-none-any.whl (444 kB)
Downloading pydantic_core-2.33.2-cp39-cp39-win_amd64.whl (2.0 MB)
   ---------------------------------------- 2.0/2.0 MB 9.1 MB/s eta 0:00:00
Downloading annotated_types-0.7.0-py3-none-any.whl (13 kB)
Downloading typing_inspection-0.4.1-py3-none-any.whl (14 kB)
Installing collected packages: typing-inspection, pydantic-core, annotated-types, pydantic

Successfully installed annotated-types-0.7.0 pydantic-2.11.7 pydantic-core-2.33.2 typing-inspection-0.4.1

In [83]:
import os, sys
sys.executable

'C:\\ProgramData\\Anaconda3\\python.exe'

In [84]:
os.getcwd()

'C:\\Users\\monke\\Repos\\eav-llm-monitor\\notebooks'

In [85]:
!pip show openai

Name: openai
Version: 1.95.1
Summary: The official Python library for the openai API
Home-page: https://github.com/openai/openai-python
Author:
Author-email: OpenAI <support@openai.com>
License: Apache-2.0
Location: c:\users\monke\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages
Requires: anyio, distro, httpx, jiter, pydantic, sniffio, tqdm, typing-extensions
Required-by:

In [3]:
import os, sys

In [6]:
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', 'src')))

In [7]:
from utils import io_utils
from utils import paths

In [8]:
openai_creds_uri = paths.get_project_root() / 'src' / 'utils' / 'openai_creds.json'
openai_creds_uri

WindowsPath('C:/Users/monke/Repos/eav-llm-monitor/src/utils/openai_creds.json')

In [10]:
openai_creds = io_utils.read_json(openai_creds_uri)

openai.api_key = openai_creds['OPENAI_API_KEY']

In [127]:
client = openai.OpenAI(api_key = openai_creds['OPENAI_API_KEY'])

In [129]:
response = client.responses.create(
    model = 'gpt-4.1',
    input = 'Tell me a joke in under 140 characters.'
)

In [130]:
response.output_text

"Why don't skeletons fight each other? They don't have the guts!"

In [133]:
from pydantic import BaseModel

In [116]:
import numpy as np

In [118]:
np.ceil(6.234)

7.0

In [129]:
'asdf\nwefqwef'.replace('\n', '')

'asdfwefqwef'

In [161]:
def estimate_tokens(s):
    """Estimate number of tokens in a given string (~n chars/token)"""
    # https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
    n = 3.8
    s = str(s)
    replace_chars = ['\n','\t',' ']
    for char in replace_chars:
        s = s.replace(char, '')
    return int(np.ceil(len(s)/n))

In [131]:
s = 'My hovercraft is full of eels.'
estimate_tokens(s)

7

's'*4*2048

In [124]:
paths.get_data_processed_path()

WindowsPath('C:/Users/monke/Repos/eav-llm-monitor/data/processed')

In [125]:
os.listdir(paths.get_data_processed_path())

['reddit_preprocessed_20250712_015736.csv',
 'reddit_preprocessed_20250713_014002.csv',
 'reddit_preprocessed_20250713_115413.csv']

In [154]:
df = None
for csv in os.listdir(paths.get_data_processed_path()):
    if df is None:
        df = pd.read_csv(paths.get_data_processed_path() / csv)
    else:
        df = pd.concat([df, pd.read_csv(paths.get_data_processed_path() / csv)])
df.reset_index(inplace=True)

In [141]:
df

,index,score,created_utc,text
0,0,3,2025-07-11 19:34:54,rivian\r\nIcon Question\r\nSo didn’t see this ...
1,1,10,2025-07-11 17:50:55,rivian\r\nTire replacement. Issues at Costco.\...
2,2,2,2025-07-11 14:24:12,rivian\r\nTesla charger issues?\r\nThe past fe...
3,3,2,2025-07-11 13:58:28,rivian\r\nVibration and humming noise from the...
4,4,4,2025-07-11 12:47:27,rivian\r\nLeft side Prox Sensors\r\nI have rec...
...,...,...,...,...
3052,38,2,2025-07-13 02:07:44,MechanicAdvice\nStarter won’t spin all the tim...
3053,39,1,2025-07-13 09:03:30,MechanicAdvice\nCivic AC compressor question\n...
3054,40,1,2025-07-13 09:12:29,MechanicAdvice\nAftermarket car starter\nPut a...
3055,41,1,2025-07-13 08:57:15,MechanicAdvice\nElectronics not workong after ...
3056,42,1,2025-07-13 06:52:32,MechanicAdvice\nCar Is Not Starting\nI drive a...

In [162]:
for i in df.index:
    tokens = estimate_tokens(df.loc[i, 'text'])
    if tokens > 2048:
        print(i, tokens)

150 7864
152 2947
165 2987
201 2101
378 3460
507 3265
509 2265
510 3916
519 2416
520 5214
526 3843
530 2145
547 2427
551 2531
573 2339
582 2424
614 2115
691 2115
708 3073
713 2887
729 3210
799 3444
816 2887
825 3668
861 2465
901 3825
913 3152
926 4548
936 7854
951 4232
1037 2145
1091 2247
1145 2145
1608 2149
1754 2540
1790 2540
1823 2149

In [150]:
print(df.loc[150, 'text'])

rivian
One Month of Ups and Downs
So it's the end of my first month of ownership and it's been a ride. I can't say it's been great, but let's see if I can be fair about describing my whole new owner experience from start to finish, from demo to despair at having my truck towed back to the service center in shame. Sometimes shit happens and the real story is not necessarily why it happened, but how it was handled.



This is a roller coaster. Buckle up and keep your arms and legs inside the vehicle at all times. Or don't I guess because this isn't mandated by law in Texas but the disclaimer you signed before going in the gate means you can't sue if this shit goes off the rails.



**TL:DR**

Vehicle: After a very long bout of researching, comparing features with the competition and waiting for years for the correct opportunity, I got what I wanted in an R1T and think they made a great thing. It was on the road for 8 days and 200 miles before suffering a number of failures and towed back to the service center.

Customer Service: Abysmal. I will make no concessions. I just about cancelled the order before it even got here but the service center saved it.

Roadside Assistance: Pretty great honestly.

Service Center (Austin): About as fast attacking the problem as any mechanic I've been to locally and reasonably responsive. Truck was towed in and was looked at within two days of getting there. Spent two weeks so far being worked on for a bad CV boot, a blocked air valve in the air suspension and a cryptic problem with the rear drive unit that an engineer was called in to look at.

**Chapter 1: The Beginning Part At The Beginning**

So I had been planning for quite a long time for the successor to my current truck to be electric. I am a technical person in a technical career from a technical family. Even if I didn't care about the positive impacts of no emissions and charging at home, I have long since come to the conclusion that electric drive trains are inherently superior and This Is The Way. The question has only been when batteries and production economics would converge into a vehicle that I both wanted and could afford. It seemed we were about to arrive in 2020 and then COVID ruined everything. I'd been waiting ever since, very much interested in the coming F-150 Lightning, Silverado EV and to see if this Rivian outfit would get off the ground.



I won't bother with the House Hunters-esque fake story about how I was jumping between these three options and had to make a decision. You already know I bought a Rivian. Gen 1 2024 R1T a week before the Gen 2 reveal. So why?



The competition was mostly down between the F-150 and the Rivian. The Silverado EV is there in a technical sense, but I wasn't willing to wait 2 more years for them to get through the early adopters, produce trims that cost less than 90k and sort out any first-year production hiccups. Too late to the game. The cybertruck was there in a technical sense too, but even if there was one selling for less than six figures, no. Just no. If the Ramcharger had been a thing 3 years earlier I'd probably have been looking over there too because my work commute would've been all-battery, but they were also too late to the game. I spent weeks and months watching the online Ford and Rivian stores for price changes and constantly comparing builds. Once we hit the Rivian price changes in April/May with the standard+ battery I realized something. If I lined up the HP, battery range and other features on the adventure R1T with a Lightning with an XLT or Lariat trim that had mostly the same things, they cost pretty much the same. The base price of the Rivian was way higher but...it came with a lot more by default. Ford has that big corporate tendency to bundle options together so you wind up spending more money. Getting the large battery on the XLT Ford meant another 15k. Not because that's what the battery cost, but because getting it required another upgrade package over the base model and one that I didn't want. It included 22" wheels, except what I wanted was the base model's 18" wheels because I wanted tires with more sidewall. Want leather seats? Platinum trim only, 92k please. And I did want leather seats, because my cloth ones were a bitch to clean with the dust around here. Is that going to motivate me to spend 15k more to 'be a tech titan' as their byline says and get that leather interior as a byproduct? No. Go home. You're drunk. GM at least lets you add that as an option by itself.



While I had a short list of what I wanted, it doesn't really pair up with EV marketing. I am tech-y, but I am not a tech enthusiast. In the car world I might be the equivalent of that sysadmin joke where they cast any IoT device out of their house, use mechanical locks on everything and only ever keep a printer at home next to a loaded gun for whenever it makes the wrong sound. Don't get me wrong, despite the hyperbole it's not about being afraid of tech. It's about maybe knowing all of its shortcomings too well. Automotive IT security for most OEMs is hilariously terrible and invasive data harvesting is endemic now. Seriously. Look at what Nissan does. I don't use most forms of phone integration or on-board navigation for those reasons. That doesn't stop tech stuff from factoring into my purchasing decisions, but it sort of does it in the opposite way. It's actually a turnoff if I'm expected to pay extra for things I don't use. Double turnoff if it's something I actively have to hunt down in its lair in deep in the interface and viscerally disable. I'll outright say L2 driver assistance has no value to me despite the fact every OEM has some form of it, because if I have to sit there 'ready to take control' at any time then I am not a passenger regaining commute time for vital stuff like sleeping or goofing off on the internet. I've read too deeply into the shortcomings of current self-driving programming to trust it. It's extremely easy to become complacent with it, or you can be constantly on your toes questioning if drifting toward the K-rail on that exit ramp is the system trying to kill you. I'd much rather the computer was the one making panicked bleating noises when it sensed the entity at the controls was doing something wrong. Well, when something was actually going wrong and not being a little dramatic because road construction was messing with lane markings, or some car ahead had turned off the road but still had a part of its ass-end in the shoulder as we went by. Adaptive cruise, blind spot monitoring and backup cameras are appreciated, but those things were common two generations ago. I'll even say ventilated seats are sweet. However I despise touchscreens for vehicle controls and it seems that at least for the near term it's both a futurism thing and a way for OEMs to cut costs. Rivians in fact seemed to have a lot of neat but ultimately overengineered widgits like actuating door handles and motorized vents that might be a pain to fix when they break. So you might be asking wtf was I doing buying one instead of an F-150 Lightning work truck? The answer to that is you can't just buy a base Lighting Pro or XLT with a leather interior, the performance motor or the bigger battery pack. You need bundles! Upgrades!



So who do you think was the worst offender in trying to get more money out of me for features I didn't care about or actively did not want?



The going method with big OEMs seems to be to stuff high trim packages with oodles of widgets like heated mirrors that make it seem like people are getting a lot for the money, while many of them cost bupkis to install at the factory and have an outsized impact on your future maintenance costs when it stops working. There's a reason the highest margin is on high trim vehicles, after all. I was actually pleased the F-150 XLT had infotainment and climate control buttons under the screen. Buttons! In 2024! But the higher trims didn't. For whatever reason tactile buttons are tools of the plebians despite being better. Given my ambivalence about Cool New Tech I probably would have held onto my current truck until the wheels fell off. Except for that one thing: Electric drive train superior. ICE inferior. I'll admit I actually feel some measure of guilt for driving a full-sized 16mpg behemoth and it seemed so petty to continue to do so another 10 years for so trivial a reason as wanting a model with the perfect set of cup holders or whatever. If I did some soul searching though the Fords feel...overpriced. Not necessarily POS on the drivetrain or engineering but I've never felt that what you got out of a Lariat+ trim with largely only interior changes was worth the extra money. Most everything under the hood is still the same. It doesn't get you better paint than the work truck. If you don't know Ford paint, well uh, you'll be perfectly fine never finding out. So anyway, where do you go if you want higher material quality and don't actually care very much about huge numbers of gadgety features common to luxury brands in the 70k+ price range?



The answer was a bit unintuitive. Regardless of whatever complaints I had, the 'luxury' Rivian seemed to be better value for the money. It was expensive, sure, but from my reading it seemed like Rivian was putting a lot behind its first run of vehicles and eating the cost to lay the foundations for a good reputation. Initial reviews were good and it seemed Rivian was at least trying to hedge against suffering initial huge bad press that would be largely impossible to recover from. I'd heard people complain Rivians were somewhat spartan compared to luxury vehicles in their price range but tended to be well built with high quality materials. The short bed was a nuisance but nobody else was making a 2-door or extended cab version truck in any size with a standard 6.5ft box. What actually pushed me to make a decision was when I was going over the full specs and encountered the scourge of Embiggification. New trucks have been getting progressively wider and taller and longer and it mattered because apparently neither the F-150 or the Silverado EV would fit in my garage. After walking past a shiny new Ram in a random parking lot with the hoodline near shoulder level something...snapped. It got my attention, but not in the good way. You know how something grabs your train of thought and throws it off the rails while saying something like "The fuck is this?" while you're trying to get to a restaurant? It wasn't even lifted! I was upset. Incensed. Maybe it was the most egregious example of a trend I'd quietly noticed in all the newest trucks with front ends a mile tall. Who did this? Why?! It was already a pain in the ass to reach the center of the hood when washing! I actually wanted smaller but would've settled for the same size I had. My predecessor truck actually did (barely) fit in the garage along with its sibling SUV, clearing the door by about 2" if I gingerly push it in neutral until it touches the wall and climb out the passenger side. It's come in handy for a couple hurricanes, hail storms and tornado warnings. I wanted to do my charging indoors and also retain the option to keep the most expensive vehicle I'd ever bought out of the weather as much as possible. The Rivian was actually smaller than any of them. A full foot shorter. A slight bit narrower. Only taller if the suspension was set to max height. And by that I mean it was about the footprint of full sized trucks from three or four model generations ago. Who else was making...mid-sized EV trucks?



I had resolved that I would never buy the first model year of a new vehicle under any circumstances. However the R1T was on its third year and hopefully the early series production bugs had been worked out and fixed on the line. The refresh was coming and demand for the inventory was probably at a low ebb. Since I wasn't going to buy a first-year Gen 2 (keep to the code!) I thought maybe my time had come. Maybe there'd be deals. To be honest I thought that since Gen 2's primary goal was to cut costs, it was entirely possible it wasn't just the same thing built more efficiently. If any cost concessions impacted durability nobody would find out until the first ones had spent a few years in the wild. That's largely speculation in the absence of any real world data, mind. Also changing that much stuff would doubtlessly create a new series of its own bugs and hiccups that would take a couple years to sort out.



So off I went to Austin to lay hands on one.



**Chapter 2: Reality Is Real and Hate Makes You Stronger**



I had seen a Rivian in the wild exactly once for a few seconds. I never had the opportunity to actually touch one. I'll be straight up, the R1T is a magnificent creature and the internet pictures didn't do it justice. Some people like angles and boxes as has been the trend of the last decade. I like curves. The psuedo side-step box with the wide, arcing fenders struck a particular chord along with the distinctive Rivian front end. Suffice it to say I was a fan. The interior was much better than I expected. The demo model had the black with ash wood. To me it seemed not just comfortable, but polished. Not unsurpassed if you were shopping the out and out luxury brands, but vastly better than the pleather-trimmed cloth I would've been able to get with an equal-priced Lightning. It didn't have a glove box or as many compartments. Didn't care.



Coming from a spring suspension full size truck it's a little hard for me to describe the difference air suspension makes. It's...wonderful. The guide deliberately took me to an area of many speedbumps, put the suspension in soft and dared me to just...hit them without slowing down. The interesting bit is how it damps road vibrations much better and not just bumps. Colour me impressed. Nothing so tall or heavy should corner that well either, but it does. Vastly less noise than anything I'd been used to driving and ultimately a very quiet vehicle. My uh, predecessor truck's base sound system at normal volume was basically inaudible over highway noise so being able to hear shit is great. I know some people are critical but that wasn't much of a sticking point for me. Once again, who else was going to deliver the vehicle that was largely the same AND had a better sound system? For the same-ish money. Also not in three years.



I spent about 2 hours there crawling over the vehicles in the lot, looking at the different colours, interiors and asking technical questions. Overall a great experience. They weren't able to answer ALL my questions because of Texas dealer laws. So I was paired up with a guide who answered the remaining purchasing questions. While I was there I also learned of the May discounts on the vehicles in the inventory. Two days after that test drive I picked one out of the shop and put a deposit down. A forest green dual motor. I wanted the EV credit and had to choose a discounted large battery (wooo sale!) over the performance upgrade.



Aaaand that's where the music stopped. Record scratch. I was under the impression that I had to complete all the purchase tasks in order to schedule delivery. I was also told that delivery had to happen by June 1 to get the sale pricing, leaving me a week and change to get that sorted so it was going to be a time crunch. So I did all the things. The day after Memorial Day I had the truck on my insurance, payment sorted and contracts signed. But as soon as I put that initial deposit down, I was ghosted. Rivian people do answer the main phone line and the chat, but you actually cannot get in contact with anyone who knows what's going on with your purchase directly. You cannot be transferred to them. You have to leave a message and they have to call, email or text you back. Except they...don't. June 1 was approaching, no tasks were outstanding, I had money down and...I had no idea if anything was happening to get things resolved by this Rivian-imposed deadline. After a few days of trying and failing to get anywhere the service center contacted me directly to say my truck had arrived at Austin and I needed to schedule delivery. Cool. Except I missed that call and needed to call them back. Did you know you also can't call the service center directly either? So I had to leave messages again and wait for someone to respond. Naturally two further days of trying resulted in no response. Well OK, surely I could schedule delivery through the Rivian website using the Schedule Delivery button if we were good to go? Also no. Fuck you. And don't call me Shirley. It was honestly the most frustrating experience I'd ever had trying to buy anything. The family was asking if I was sure I wasn't getting scammed. I was so pissed off that I was ready to cancel the order and stop all payments, because if I couldn't get someone to answer the goddam phone in the span of a week for $80 000, how bad was service going to be?



In the end the service center left me a number on which I could call them back directly and I was able to finally schedule delivery. It didn't happen by June 1st, but I would keep the sale price. Cool. Well sorta cool. I had to give up making any modifications to the order because it was too late. I had wanted 20" wheels because I didn't like the (lack of) options for the 21" and wanted the extra sidewall. That had been negotiated with my guide the day after the test drive, but went nowhere because after I put the deposit down I couldn't contact anyone who could sell them to me. So I had to accept the 21" or cancel the order and get a different truck already fitted with the 20s. I grumbled and carried on. The next week a different guide-person contacted me to say there was a problem with the paperwork. Apparently the state of Texas does not consider an Evidence of Insurance document from my insurer to be proof of insurance. While that's ironic in its absurdity, THAT is what finally got a guide to contact me after two weeks of ignored messages and emails. Glowering at the screen was all I could do.



During that same time I ordered some stuff from the Rivian store including a wall charger. I was in the process of getting a 240V service set up in my garage, but a week after I ordered the thing it still hadn't shipped.  I was going to lose my electrician and needed to know when it was going to ship. Days? Weeks? Tried to contact customer service. Same deal. Email, phone, chat. Could never contact anyone who could tell me anything about the order and the guide people never called, texted or emailed back. Think I ran 0 for 7 attempts over 3 days. Wound up cancelling it through the chat agent, who was left to send the sales people a message, installing a 240V plug in the garage and getting a Grizzl-e off Amazon. Except it shipped anyway and sat with me for two weeks before I got a return label, which I had to somewhat unkindly extort by threatening a chargeback. That $800 is still out of pocket.



I didn't even have the truck yet and I was getting a sinking feeling. This was not the way a well-run company operates. Or as my father more diplomatically put it when discussing the situation 'What sort of fucked up shit-show is this?' You can call it being dramatic in the heat of the moment, but I have no kind words for that whole experience. It took all I had to just not be a dick to the people in the call center and chats trying to get through to someone, because it wasn't like it was specifically their fault nobody was ever responding.



**Chapter 3: A Small World With Ice Cream and Rainbows**




In [136]:
i

131

In [132]:
df.index

Int64Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
            ...
            33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
           dtype='int64', length=3057)

In [138]:
df.loc[0]

,score,created_utc,text
0,3,2025-07-11 19:34:54,rivian\r\nIcon Question\r\nSo didn’t see this ...
0,1,2025-07-13 01:20:00,rivian\nTest Drive\nWith the Federal EV rebate...
0,5,2025-07-13 11:27:01,rivian\nDIY or call service?\nI have Gen2 R1S ...

In [104]:
from utils import io_utils
from utils import paths
import openai
import numpy as np
import os

# create OpenAI client
openai_creds_uri = paths.get_project_root() / 'src' / 'utils' / 'openai_creds.json'
openai_creds = io_utils.read_json(openai_creds_uri)
client = openai.OpenAI(api_key = openai_creds['OPENAI_API_KEY'])

def estimate_tokens(s):
    """Estimate number of tokens in a given string (~n chars/token)"""
    # https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them
    n = 3.8
    s = str(s)
    replace_chars = ['\n','\t',' ']
    for char in replace_chars:
        s = s.replace(char, '')
    return int(np.ceil(len(s)/n))

def query_openai(query, instructions, temperature=0, model='gpt-4o-mini', top_p=1.0, max_tokens=256): #'gpt-4.1'
    """Query openai with given parameters, returns the response"""
    
    response = client.responses.create(
        model = 'gpt-4.1',
        input = query,
        instructions = instructions,
        temperature = temperature,
        max_tokens = max_tokens,
        top_p = top_p
    )
    
    return response
    
def construct_query_instructions(source='reddit', shot=0):
    """Reads and formats instructions for openai api"""
    instructions_uri = paths.get_project_root() / 'src' / 'llm' / 'instructions.json'
    all_instructions = io_utils.read_json(instructions_uri)
    if source not in all_instructions.keys():
        source = 'reddit'
    instructions_dict = io_utils.read_json(instructions_uri)[source]
    
    # Identity
    instructions = "# Identity\n"
    instructions += instructions_dict['identity']
    instructions += '\n\n'
    
    # Instructions
    instructions += "# Instructions"
    instructions_list = instructions_dict['instructions']
    for instr in instructions_list:
        instructions += f"\n* {instr}"
    
    # Examples ()
    if shot > 0:
        instructions += "\n\n# Examples"
    examples = instructions_dict['examples']
    if shot > len(examples):
        shot = len(examples)
    for _ in range(shot):
        i = random.choice(range(len(examples)))
        example = examples.pop(i)
        instructions += f"\n\n<user_query> {example['user_query']} </user_query>\n"
        instructions += f"<assistant_response> {example['assistant_response']} </assistant_response>"
        
    return instructions



if __name__ == "__main__":
    

query = """rivian
Vibration and humming noise from the front end
I have a late 2022 R1T (11/22 build date) with 37k miles. Rivian SC replaced my front axles and hubs/bearings about a month ago. When I picked it up I started hearing a hollow humming noise from my front end (feels like front left wheel). I've had them look at it last week and they said everything is fine and that it must be my ""aftermarket"" tires (brand new 21"" Michelin Defenders). They seem to be unwilling to diagnose it further unless I put Pirellis back on there. It's mostly noticeable at high speeds but now that I've tuned into it I hear it at lower speed as well. Jumping on the freeway today it has gotten louder, I'll try and record a video clip.

Has anybody had an issue like this before?"""
query = """rivian
Tesla charger issues?
The past few times I’ve tried charging at a public Tesla supercharger, I’ve had nothing but issues. Currently, I’m sitting at the only one in the area while it says “starting” with a circling wheel for 10 minutes and losing battery. Tesla issue, or my car issue? No problem at non-Tesla branded chargers and no issue at home with my Tesla branded charger w/converter"""

instructions = construct_query_instructions()

response = client.responses.create(
    model = 'gpt-4.1',
    input = query,
    instructions = instructions,
    temperature = 0
)

In [89]:
response.output_text

'{"is_rivian": "Yes", "is_issue": "Yes", "system": "suspension", "severity": "Medium", "firsthand": "Yes"}'

In [105]:
response.output_text

'{"is_rivian": "Yes", "is_issue": "Yes", "system": "charging", "severity": "Medium", "firsthand": "Yes"}'

In [103]:
response.usage

ResponseUsage(input_tokens=424, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=38, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=462)

In [111]:
response

Response(id='resp_687408d7ef3881a2afd076580b3732610757323915d0e091', created_at=1752434903.0, error=None, incomplete_details=None, instructions='# Identity\nYou are a structured classifier that analyzes Reddit posts to determine whether they describe a reliability issue involving a Rivian electric vehicle. You return answers in a strict JSON format for downstream processing.\n\n# Instructions\n* Always begin by checking whether the post is about a Rivian vehicle.\n* Determine whether the post describes a reliability issue (e.g., a problem or malfunction).\n* Identify which vehicle system is affected, using one of the following categories: \'battery\', \'charging\', \'infotainment\', \'software\', \'brakes\', \'suspension\', or \'unknown\'.\n* Rate the severity of the issue as one of: \'Low\', \'Medium\', or \'High\'.\n* Indicate whether the post describes a firsthand account (the author directly experienced the issue).\n* Return all results in the following strict JSON format: {"is_rivian": "Yes|No", "is_issue": "Yes|No", "system": "<system>", "severity": "Low|Medium|High", "firsthand": "Yes|No"}\n* Do not add any explanation, markdown formatting, or commentary - return only the JSON object.', metadata={}, model='gpt-4.1-2025-04-14', object='response', output=[ResponseOutputMessage(id='msg_687408d8609481a2a90e3cc387ba98ea0757323915d0e091', content=[ResponseOutputText(annotations=[], text='{"is_rivian": "Yes", "is_issue": "Yes", "system": "charging", "severity": "Medium", "firsthand": "Yes"}', type='output_text', logprobs=[])], role='assistant', status='completed', type='message')], parallel_tool_calls=True, temperature=0.0, tool_choice='auto', tools=[], top_p=1.0, background=False, max_output_tokens=None, max_tool_calls=None, previous_response_id=None, prompt=None, reasoning=Reasoning(effort=None, generate_summary=None, summary=None), service_tier='default', status='completed', text=ResponseTextConfig(format=ResponseFormatText(type='text')), top_logprobs=0, truncation='disabled', usage=ResponseUsage(input_tokens=332, input_tokens_details=InputTokensDetails(cached_tokens=0), output_tokens=36, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=368), user=None, store=True)

In [17]:
instructions_uri = paths.get_project_root() / 'src' / 'llm' / 'instructions.json'
instructions_dict = io_utils.read_json(instructions_uri)['reddit']

In [18]:
instructions_dict.keys()

dict_keys(['identity', 'instructions', 'examples'])

In [19]:
instructions_dict['examples']

[{'user_query': "Post: 'My Rivian R1T lost power while driving on the highway. This is the third time this month.'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "Yes", "system": "battery", "severity": "High", "firsthand": "Yes"}'},
 {'user_query': "Post: 'I heard someone mention that their friend's Rivian app crashed again, not sure if it's widespread.'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "Yes", "system": "infotainment", "severity": "Low", "firsthand": "No"}'},
 {'user_query': "Post: 'Tesla just announced a new range update! Might make Rivian nervous.'",
  'assistant_response': '{"is_rivian": "No", "is_issue": "No", "system": "unknown", "severity": "Low", "firsthand": "No"}'},
 {'user_query': "Post: 'My R1S screen froze again while reversingâ€”thankfully nothing was behind me. Anyone else?'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "Yes", "system": "infotainment", "severity": "Medium", "firsthand": "Yes"}'},
 {'user_query': "Post: 'Love my Rivian so far! Just wish the regen braking felt smoother on downhills.'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "Yes", "system": "brakes", "severity": "Low", "firsthand": "Yes"}'},
 {'user_query': "Post: 'A friend of mine said his R1T's suspension collapsed going over a pothole. That's terrifying.'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "Yes", "system": "suspension", "severity": "High", "firsthand": "No"}'},
 {'user_query': "Post: 'Does anyone know if the recent software update improved the charging station compatibility?'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "No", "system": "charging", "severity": "Low", "firsthand": "No"}'},
 {'user_query': "Post: 'After two months with the R1S, I've had no major issues. Range holds up even in the cold!'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "No", "system": "unknown", "severity": "Low", "firsthand": "Yes"}'},
 {'user_query': "Post: 'The frunk on my R1T won't latch properly anymore. Minor thing, but annoying.'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "Yes", "system": "unknown", "severity": "Low", "firsthand": "Yes"}'},
 {'user_query': "Post: 'I'm researching EVsâ€”Tesla vs Rivian vs Ford. Reliability is a big factor for me.'",
  'assistant_response': '{"is_rivian": "Yes", "is_issue": "No", "system": "unknown", "severity": "Low", "firsthand": "No"}'}]

In [51]:
instructions_dict['instructions']

['Always begin by checking whether the post is about a Rivian vehicle.',
 'Determine whether the post describes a reliability issue (e.g., a problem or malfunction).',
 "Identify which vehicle system is affected, using one of the following categories: 'battery', 'charging', 'infotainment', 'software', 'brakes', 'suspension', or 'unknown'.",
 "Rate the severity of the issue as one of: 'Low', 'Medium', or 'High'.",
 'Indicate whether the post describes a firsthand account (the author directly experienced the issue).',
 'Return all results in the following strict JSON format: {"is_rivian": "Yes|No", "is_issue": "Yes|No", "system": "<system>", "severity": "Low|Medium|High", "firsthand": "Yes|No"}',
 'Do not add any explanation, markdown formatting, or commentaryâ€”return only the JSON object.']

In [69]:
def construct_query_instructions(shot=0):
    instructions_uri = paths.get_project_root() / 'src' / 'llm' / 'instructions.json'
    instructions_dict = io_utils.read_json(instructions_uri)['reddit']
    
    # Identity
    instructions = "# Identity\n"
    instructions += instructions_dict['identity']
    instructions += '\n\n'
    
    # Instructions
    instructions += "# Instructions"
    instructions_list = instructions_dict['instructions']
    for instr in instructions_list:
        instructions += f"\n* {instr}"
    
    # Examples ()
    if shot > 0:
        instructions += "\n\n# Examples"
    examples = instructions_dict['examples']
    if shot > len(examples):
        shot = len(examples)
    for _ in range(shot):
        i = random.choice(range(len(examples)))
        example = examples.pop(i)
        instructions += f"\n\n<user_query> {example['user_query']} </user_query>\n"
        instructions += f"<assistant_response> {example['assistant_response']} </assistant_response>"
        
    return instructions

In [70]:
print(construct_query_instructions(shot=2))

# Identity
You are a structured classifier that analyzes Reddit posts to determine whether they describe a reliability issue involving a Rivian electric vehicle. You return answers in a strict JSON format for downstream processing.

# Instructions
* Always begin by checking whether the post is about a Rivian vehicle.
* Determine whether the post describes a reliability issue (e.g., a problem or malfunction).
* Identify which vehicle system is affected, using one of the following categories: 'battery', 'charging', 'infotainment', 'software', 'brakes', 'suspension', or 'unknown'.
* Rate the severity of the issue as one of: 'Low', 'Medium', or 'High'.
* Indicate whether the post describes a firsthand account (the author directly experienced the issue).
* Return all results in the following strict JSON format: {"is_rivian": "Yes|No", "is_issue": "Yes|No", "system": "<system>", "severity": "Low|Medium|High", "firsthand": "Yes|No"}
* Do not add any explanation, markdown formatting, or commentary - return only the JSON object.

# Examples

<user_query> 'Tesla just announced a new range update! Might make Rivian nervous.' </user_query>
<assistant_response> {"is_rivian": "No", "is_issue": "No", "system": "unknown", "severity": "Low", "firsthand": "No"} </assistant_response>

<user_query> 'After two months with the R1S, I've had no major issues. Range holds up even in the cold!' </user_query>
<assistant_response> {"is_rivian": "Yes", "is_issue": "No", "system": "unknown", "severity": "Low", "firsthand": "Yes"} </assistant_response>

In [ ]:
import openai
from utils import io_utils
from utils import paths
import random
# from pydantic import BaseModel

openai_creds_uri = paths.get_project_root() / 'src' / 'utils' / 'openai_creds.json'
openai_creds = io_utils.read_json(openai_creds_uri)
client = openai.OpenAI(api_key = openai_creds['OPENAI_API_KEY'])

input_prompt = 'Tell me a joke in under 140 characters.'

response = client.responses.create(
    model = 'gpt-4.1',
    input = input_prompt,
    temperature = 0
)

reply = response.output_text
print(reply)

In [ ]:
response = client.responses.create(
    model = 'gpt-4.1',
    input = 'Tell me a joke in under 140 characters.',
    temperature = 0
)

notes

https://platform.openai.com/docs/overview
https://platform.openai.com/settings/organization/usage
https://www.anthropic.com/api
https://console.anthropic.com/workbench/d82cb9fc-9fce-4c47-aa82-951e6efd35e7
https://www.youtube.com/results?search_query=agentic+ai
https://www.youtube.com/watch?v=FwOTs4UxQS4
https://academy.jeffsu.org/ai-toolkit-confirmation-page
https://www.youtube.com/watch?v=-pqzyvRp3Tc

https://platform.openai.com/docs/models/compare
https://platform.openai.com/docs/api-reference/responses/get
https://platform.openai.com/docs/guides/text?api-mode=responses
https://platform.openai.com/docs/guides/structured-outputs?api-mode=responses&example=chain-of-thought
https://platform.openai.com/docs/guides/text?api-mode=responses&prompt-templates-examples=simple&prompt-example=prompt

In [13]:
from utils import io_utils
from utils import paths
import pandas as pd


def preprocess_reddit_raw(csvs):
    """Takes a list of reddit_raw csvs, saves preprocessed data, return if successful"""

    preprocessed = None
    data_processed = False
    
    for csv in csvs:
        df = pd.read_csv(paths.get_data_raw_path() / csv)

        # check for empty csvs
        if len(df) == 0:
            continue
        data_processed = True
        
        # drop ['Weekly Roundup']
        df.drop(df[df['title'].apply(lambda s: '[Weekly Roundup]' in s)].index, inplace=True)
        
        # combine subreddit+title+selftext
        df['text'] = df['subreddit'] + '\n' + df['title'] + '\n' + df['selftext']
        
        # drop rows with score < 0
        df.drop(df[df['score']<0].index, inplace=True)
        
        # drop unneeded columns
        df.drop(['subreddit', 'title', 'selftext','url','permalink'], axis=1, inplace=True)

        if preprocessed is None:
            preprocessed = df
        else:
            preprocessed = pd.concat([preprocessed, df])

    if data_processed:
        save_uri = paths.get_data_raw_path() / max(csvs).replace('raw', 'preprocessed')
        preprocessed.to_csv(save_uri, index=False)
    
    return data_processed


if __name__ == "__main__":

    # get last processed csv and preprocess all csvs after
    last_processed_uri = paths.get_project_root() / 'src' / 'preprocess' / 'last_processed.json'
    last_processed = io_utils.read_json(last_processed_uri)

    if 'reddit' not in last_processed.keys():
        last_processed['reddit'] = ''
    
    csvs = [csv for csv in os.listdir(paths.get_data_raw_path()) if 'reddit_raw' in csv]
    
    if (last_processed['reddit'] != '') and (last_processed['reddit'] in csvs):
        csvs = csvs[csvs.index(last_processed['reddit']) + 1:]

    data_processed = preprocess_reddit_raw(csvs)

    # update last_processed.json
    if data_processed:
        last_processed['reddit'] = max(csvs)
        io_utils.write_json(last_processed, last_processed_uri)

In [108]:
save_uri = paths.get_data_raw_path() / max(csvs).replace('raw', 'preprocessed')
save_uri

PosixPath('/Users/giancarlofgarbagnati/Projects/github/eav-llm-monitor/data/raw/reddit_preprocessed_20250712_015736.csv')

In [111]:
max(csvs)

'reddit_raw_20250712_015736.csv'

In [103]:
last_processed_uri = paths.get_project_root() / 'src' / 'preprocess' / 'last_processed.json'
last_processed = io_utils.read_json(last_processed_uri)

if 'reddit' not in last_processed.keys():
    last_processed['reddit'] = ''

csvs = [csv for csv in os.listdir(paths.get_data_raw_path()) if 'reddit_raw' in csv]
csvs

['reddit_raw_20250712_015736.csv',
 'reddit_raw_20250711_024610.csv',
 'reddit_raw_20250711_024659.csv']

In [100]:


if (last_processed['reddit'] != '') and (last_processed['reddit'] in csvs):
    csvs = csvs[csvs.index(last_processed['reddit']) + 1:]
csvs

['reddit_raw_20250711_024659.csv']

In [60]:
subreddits = ['rivian', 'electricvehicles', 'ElectricCars']
subreddits += ['CarRepair', 'autorepair', 'MechanicAdvice']
subreddits += ['DIYAutoRepair', 'AutoMechanics']

search_terms = ['broke down', 'issue', 'charging problem', 'reliability', 'won’t start']

In [76]:
import os, sys

In [77]:
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), '..', 'src')))

In [78]:
from utils import io_utils

In [98]:
import praw
import pandas as pd
from datetime import datetime

In [79]:
os.getcwd()

'C:\\Users\\monke\\Repos\\eav-llm-monitor\\notebooks'

In [94]:
reddit_creds_uri = '..\\src\\utils\\reddit_creds.json'
# os.listdir(reddit_creds_uri)

In [95]:
reddit_creds = io_utils.read_json(reddit_creds_uri)

In [97]:
reddit_creds.keys()

dict_keys(['REDDIT_CLIENT_ID', 'REDDIT_SECRET', 'REDDIT_USER_AGENT'])

In [100]:
reddit = praw.Reddit(
    client_id = reddit_creds['REDDIT_CLIENT_ID'],
    client_secret = reddit_creds['REDDIT_SECRET'],
    user_agent = reddit_creds['REDDIT_USER_AGENT']
)

In [106]:
subreddits = ['rivian', 'electricvehicles', 'ElectricCars']
# subreddits += ['CarRepair', 'autorepair', 'MechanicAdvice']
# subreddits += ['DIYAutoRepair', 'AutoMechanics']

In [108]:
keywords = ['broke down', 'issue', 'charging problem', 'reliability', "won't start"]

In [107]:
results = []

In [111]:
sub = 'rivian'

In [112]:
term = 'broke down'

In [113]:
for post in reddit.subreddit(sub).search(term, sort='new', limit = 100):
    results.append({
        'subreddit': sub,
        'title': post.title,
        'selftext': post.selftext,
        'score': post.score,
        'created_utc': datetime.fromtimestamp(post.created_utc),
        'url': post.url,
        'permalink': f"https://www.reddit.com{post.permalink}"
    })

In [115]:
len(results)

38

In [117]:
results[2]

{'subreddit': 'rivian',
 'title': 'Leased 2 Rivians in March. Both are in the service center. It’s been hell.',
 'selftext': 'So, my wife and I leased 2 Rivians to take advantage of the $200 off per month lease. I got the T, she got the S. My T broke down in the middle of the interstate with less than 350 miles on it. It’s been in the shop since early April, and they had to replace the 12v battery, ac compressor, and the pyrofuse(?) Not sure what that one is, but their target pickup date is next Wednesday. Their initial diagnosis was that they needed to replace the high voltage battery, but that’s been ruled out for now.\n\nWhen the T was in the center, they set me up with a rental. It was horrible. I got a loaner after complaining that I can’t drive the rental because I needed a truck for work. So since, I’ve been driving the T loaner, and the card key is a nightmare to use.\n\nThen I found some blue/green liquid under my wife’s S in the garage floor after she took it out for work. So I searched online and found stories where the car had to be towed to be serviced at the center. So I made a service claim and sent pictures. Lo and behold, they sent a tow truck to pick it up. No estimated date yet. And no loaner.\n\nNow we are regretting getting Rivians. Even after this whole thing gets fixed, still leaves a bad taste. \n\nI know cars can have problems and finding it out now rather than a year out is better, but not being able to drive my car that I’m paying for a month now is frustrating. \n\nAre we just bad luck or is this pretty common for new Rivians?',
 'score': 180,
 'created_utc': datetime.datetime(2025, 5, 9, 8, 28, 21),
 'url': 'https://www.reddit.com/r/Rivian/comments/1kilamq/leased_2_rivians_in_march_both_are_in_the_service/',
 'permalink': 'https://www.reddit.com/r/Rivian/comments/1kilamq/leased_2_rivians_in_march_both_are_in_the_service/'}

In [118]:
results[2]['created_utc']

datetime.datetime(2025, 5, 9, 8, 28, 21)

In [124]:
x = datetime(2005, 6, 23, 0, 0, 0)
y = datetime(2025, 5, 9, 8, 28, 21)

In [125]:
y > x

True

In [137]:
p = paths.get_project_root()

In [141]:
p.as_uri()

'file:///C:/Users/monke/Repos/eav-llm-monitor'

In [145]:
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')

In [147]:
paths.get_data_raw_path() / f'reddit_{timestamp}.csv'

WindowsPath('C:/Users/monke/Repos/eav-llm-monitor/data/raw/reddit_20250711_020056.csv')

In [ ]:
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
filename = f'{}{timestamp}.csv'

In [160]:
data_datetime_fmt = '%Y%m%d_%H%M%S'

In [171]:
def find_latest_reddit_timestamp():
    """Find the latest timestamp from the reddit raw data files"""
    latest_data_csv = [csv for csv in os.listdir(paths.get_data_raw_path()) if 'reddit' in csv]
    if len(latest_data_csv) == 0:
        return None
    latest_data_csv = max(latest_data_csv)
    datetime_str = latest_data_csv.replace('reddit_raw_','').replace('.csv', '')
    return datetime.strptime(datetime_str, data_datetime_fmt)

In [172]:
find_latest_reddit_timestamp()

datetime.datetime(2025, 7, 11, 2, 2, 51)

In [151]:
[csv for csv in os.listdir(paths.get_data_raw_path()) if 'reddit' in csv]

['reddit_raw_20250711_020251.csv']

In [164]:
s = 'reddit_raw_20250711_020251.csv'.replace('reddit_raw_','').replace('.csv', '')
s

'20250711_020251'

In [161]:
datetime.strptime(s, data_datetime_fmt)

datetime.datetime(2025, 7, 11, 2, 2, 51)

In [162]:
l = ['reddit_raw_20250701_020251.csv',
'reddit_raw_20250706_020251.csv',
'reddit_raw_20250715_020251.csv',
'reddit_raw_20250711_020251.csv']

In [163]:
max(l)

'reddit_raw_20250715_020251.csv'

In [167]:
max([])

ValueError: max() arg is an empty sequence

In [174]:
reddit_creds_uri

'..\\src\\utils\\reddit_creds.json'

In [177]:
reddit_creds_uri = paths.get_project_root() / 'src' / 'utils' / 'reddit_creds.json'
reddit_creds_uri

WindowsPath('C:/Users/monke/Repos/eav-llm-monitor/src/utils/reddit_creds.json')

In [102]:
import os
from utils import io_utils
from utils import paths
import praw
import pandas as pd
from datetime import datetime

""" Praw resources
https://praw.readthedocs.io/en/stable/index.html
https://praw.readthedocs.io/en/stable/code_overview/reddit_instance.html
https://praw.readthedocs.io/en/stable/code_overview/models/subreddit.html
"""

# praw setup
reddit_creds_uri = paths.get_project_root() / 'src' / 'utils' / 'reddit_creds.json'
reddit_creds = io_utils.read_json(reddit_creds_uri)
reddit = praw.Reddit(
    client_id = reddit_creds['REDDIT_CLIENT_ID'],
    client_secret = reddit_creds['REDDIT_SECRET'],
    user_agent = reddit_creds['REDDIT_USER_AGENT']
)

data_datetime_fmt = '%Y%m%d_%H%M%S'

def scrape_reddit(subreddits, search_terms, last_update=None, limit=100):
    """Scrapes various subreddits for various terms and returns as a df"""
    if last_update is None:
        last_update = datetime(2005, 6, 23, 0, 0, 0) # beginning of reddit
    
    results = []
    
    for sub in subreddits:
        for term in search_terms:
            print(f'Searching r/{sub} for "{term}"...')
            for post in reddit.subreddit(sub).search(term, sort='new', limit=limit):
                post_timestamp = datetime.fromtimestamp(post.created_utc)
                if post_timestamp > last_update:
                    results.append({
                        'subreddit': sub,
                        'title': post.title,
                        'selftext': post.selftext,
                        'score': post.score,
                        'created_utc': post_timestamp,
                        'url': post.url,
                        'permalink': f"https://www.reddit.com{post.permalink}"
                    })
    
    return pd.DataFrame(results)

def find_latest_reddit_timestamp():
    """Find the latest timestamp from the reddit raw data files"""
    latest_data_csv = [csv for csv in os.listdir(paths.get_data_raw_path()) if 'reddit' in csv]
    if len(latest_data_csv) == 0:
        return None
    latest_data_csv = max(latest_data_csv)
    datetime_str = latest_data_csv.replace('reddit_raw_','').replace('.csv', '')
    return datetime.strptime(datetime_str, data_datetime_fmt)

if __name__ == "__main__":
    subreddits = ['rivian', 'electricvehicles', 'ElectricCars']
    subreddits += ['CarRepair', 'autorepair', 'MechanicAdvice']
    subreddits += ['DIYAutoRepair', 'AutoMechanics']
    
    search_terms = ['broke down', 'issue', 'charging problem', 'reliability', 'won’t start']
    
    df = scrape_reddit(subreddits, search_terms, last_update = find_latest_reddit_timestamp())
    
    timestamp = datetime.now().strftime(data_datetime_fmt)
    filename = paths.get_data_raw_path() / f'reddit_raw_{timestamp}.csv'
    if len(df) > 0:
        df.to_csv(filename, index=False)
    print('Reddit finished scraping')
    print(f'{timestamp}')
    if len(df) > 0:
        print(f'{len(df)} results, saved as {filename}')
    else:
        print(f'{len(df)} results, not saved')

Searching r/rivian for "broke down"...
Searching r/rivian for "issue"...
Searching r/rivian for "charging problem"...
Searching r/rivian for "reliability"...
Searching r/rivian for "won’t start"...
Searching r/electricvehicles for "broke down"...
Searching r/electricvehicles for "issue"...
Searching r/electricvehicles for "charging problem"...
Searching r/electricvehicles for "reliability"...
Searching r/electricvehicles for "won’t start"...
Searching r/ElectricCars for "broke down"...
Searching r/ElectricCars for "issue"...
Searching r/ElectricCars for "charging problem"...
Searching r/ElectricCars for "reliability"...
Searching r/ElectricCars for "won’t start"...
Searching r/CarRepair for "broke down"...
Searching r/CarRepair for "issue"...
Searching r/CarRepair for "charging problem"...
Searching r/CarRepair for "reliability"...
Searching r/CarRepair for "won’t start"...
Searching r/autorepair for "broke down"...
Searching r/autorepair for "issue"...
Searching r/autorepair for "charging problem"...
Searching r/autorepair for "reliability"...
Searching r/autorepair for "won’t start"...
Searching r/MechanicAdvice for "broke down"...
Searching r/MechanicAdvice for "issue"...
Searching r/MechanicAdvice for "charging problem"...
Searching r/MechanicAdvice for "reliability"...
Searching r/MechanicAdvice for "won’t start"...
Searching r/DIYAutoRepair for "broke down"...
Searching r/DIYAutoRepair for "issue"...
Searching r/DIYAutoRepair for "charging problem"...
Searching r/DIYAutoRepair for "reliability"...
Searching r/DIYAutoRepair for "won’t start"...
Searching r/AutoMechanics for "broke down"...
Searching r/AutoMechanics for "issue"...
Searching r/AutoMechanics for "charging problem"...
Searching r/AutoMechanics for "reliability"...
Searching r/AutoMechanics for "won’t start"...
Reddit finished scraping
20250712_015736
134 results, saved as /Users/giancarlofgarbagnati/Projects/github/eav-llm-monitor/data/raw/reddit_raw_20250712_015736.csv

In [128]:
os.getcwd()

'C:\\Users\\monke\\Repos\\eav-llm-monitor\\notebooks'

In [130]:
Path().resolve()

WindowsPath('C:/Users/monke/Repos/eav-llm-monitor/notebooks')

In [132]:
Path(__file__).resolve()

NameError: name '__file__' is not defined

In [65]:
import praw

In [66]:
reddit_creds_uri = paths.get_project_root() / 'src' / 'utils' / 'reddit_creds.json'
reddit_creds = io_utils.read_json(reddit_creds_uri)
reddit = praw.Reddit(
    client_id = reddit_creds['REDDIT_CLIENT_ID'],
    client_secret = reddit_creds['REDDIT_SECRET'],
    user_agent = reddit_creds['REDDIT_USER_AGENT']
)

In [67]:
limit = 50

In [77]:
sub = 'electricvehicles'
term = 'broke down "rivian"'

In [78]:
results = reddit.subreddit(sub).search(term, sort='new', limit=limit)

In [82]:
for post in results:
    print(post.title)
    print(post.selftext)
    print(post.score)
    break

Rivian has a "Drive Unit" problem
Posting my experience to raise awareness:

I recently purchased a brand-new 2025 Rivian R1S, but just 24 hours and 10 miles into owning it, the vehicle broke down. The driver's console displayed a "Driving Disabled" message, along with a prompt to "Service your SUV" (see the image here: https://ibb.co/Wz3n3fL).

After struggling to get clear answers, I was first told the issue was related to a sensor. However, after the vehicle was on it's way to be returned to me, it broke down again. This time, Rivian informed me that the problem was with the "drive unit," which needed to be replaced.

It’s been two weeks since i had the car for ONE day, and I'm still waiting for any progress. Despite asking for a refund or a replacement vehicle, Rivian has refused. To make matters worse, they haven’t provided a loaner car while mine is being repaired.

This shouldn’t happen with any new car, especially one costing around $100,000. I’m left angry/frustrated, waiting for a resolution??, and hoping others will take note of these recurring issues.

________________________________________________

Link to two other examples of the same thing that happened to my Rivian:

(1)https://www.rivianownersforum.com/threads/drive-unit-failure-while-taking-delivery.6412/?utm_source=chatgpt.com

(2)https://www.rivianforums.com/forum/threads/picked-up-r1s-3-31-2024-broke-two-blocks-later-followed-by-a-catastrophic-failure.25944/?utm_source=chatgpt.com

__________________________________________________

**Edit 12/6/24** Just came across, thought it may help some of the Rivian die-hards:  https://www.teslarati.com/rivian-consumer-reports-2024-worst-brands/

**Edit 12/6/24 part 2** LOL as I was looking at the top posts for today I came across this as well:  https://old.reddit.com/r/electricvehicles/comments/1h8ec0u/rivian_ranked_dead_last_in_consumer_reports/

In [83]:
post.score

0

In [8]:

import pandas as pd
from datetime import datetime

In [25]:
import time
import pandas as pd
import undetected_chromedriver as uc
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from datetime import datetime

In [ ]:
queries = [
        '"electric vehicle" reliability since:2024-01-01',
        '"rivian problem" since:2024-01-01'
    ]

In [51]:
search_term = '"grok"'
encoded_query = search_term.replace(" ", "%20")

In [52]:
url = f"https://twitter.com/search?q={encoded_query}&src=typed_query&f=live"

options = uc.ChromeOptions()
options.headless = True
options.add_argument("--no-sandbox")
options.add_argument("--disable-gpu")
options.add_argument("--disable-dev-shm-usage")

In [62]:
options = uc.ChromeOptions()
options.add_argument("--user-data-dir=/Users/monke/Library/Application Support/Google/Chrome")  # or Windows equivalent
options.add_argument("--profile-directory=Default")  # or "Profile 1", etc.

In [63]:
driver = uc.Chrome(options=options)

In [64]:
driver.get(url)

In [56]:
tweet_data = set()

In [57]:
cards = driver.find_elements(By.XPATH, '//article[@data-testid="tweet"]')

In [58]:
cards

[]

In [59]:
url

'https://twitter.com/search?q="grok"&src=typed_query&f=live'

In [12]:
for i, q in enumerate(queries):
    print(i, q)

0 "electric vehicle" reliability since:2024-01-01
1 "rivian problem" since:2024-01-01

In [13]:
query = q

In [15]:
scrape = sntwitter.TwitterSearchScraper(query)

In [19]:
tweets = []

In [20]:
for i, tweet in enumerate(scrape.get_items()):
    tweets.append({
         'date': tweet.date,
        'username': tweet.user.username,
        'content': tweet.content,
        'url': tweet.url,
        'id': tweet.id
    })

Error retrieving https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22%5C%22rivian%20problem%5C%22%20since%3A2024-01-01%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D: blocked (404)
4 requests to https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22%5C%22rivian%20problem%5C%22%20since%3A2024-01-01%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D failed, giving up.
Errors: blocked (404), blocked (404), blocked (404), blocked (404)

ScraperException: 4 requests to https://twitter.com/i/api/graphql/7jT5GT59P8IFjgxwqnEdQw/SearchTimeline?variables=%7B%22rawQuery%22%3A%22%5C%22rivian%20problem%5C%22%20since%3A2024-01-01%22%2C%22count%22%3A20%2C%22product%22%3A%22Latest%22%2C%22withDownvotePerspective%22%3Afalse%2C%22withReactionsMetadata%22%3Afalse%2C%22withReactionsPerspective%22%3Afalse%7D&features=%7B%22rweb_lists_timeline_redesign_enabled%22%3Afalse%2C%22blue_business_profile_image_shape_enabled%22%3Afalse%2C%22responsive_web_graphql_exclude_directive_enabled%22%3Atrue%2C%22verified_phone_label_enabled%22%3Afalse%2C%22creator_subscriptions_tweet_preview_api_enabled%22%3Afalse%2C%22responsive_web_graphql_timeline_navigation_enabled%22%3Atrue%2C%22responsive_web_graphql_skip_user_profile_image_extensions_enabled%22%3Afalse%2C%22tweetypie_unmention_optimization_enabled%22%3Atrue%2C%22vibe_api_enabled%22%3Atrue%2C%22responsive_web_edit_tweet_api_enabled%22%3Atrue%2C%22graphql_is_translatable_rweb_tweet_is_translatable_enabled%22%3Atrue%2C%22view_counts_everywhere_api_enabled%22%3Atrue%2C%22longform_notetweets_consumption_enabled%22%3Atrue%2C%22tweet_awards_web_tipping_enabled%22%3Afalse%2C%22freedom_of_speech_not_reach_fetch_enabled%22%3Afalse%2C%22standardized_nudges_misinfo%22%3Atrue%2C%22tweet_with_visibility_results_prefer_gql_limited_actions_policy_enabled%22%3Afalse%2C%22interactive_text_enabled%22%3Atrue%2C%22responsive_web_text_conversations_enabled%22%3Afalse%2C%22longform_notetweets_rich_text_read_enabled%22%3Afalse%2C%22longform_notetweets_inline_media_enabled%22%3Afalse%2C%22responsive_web_enhance_cards_enabled%22%3Afalse%2C%22responsive_web_twitter_blue_verified_badge_is_enabled%22%3Atrue%7D failed, giving up.

In [18]:
tweets

NameError: name 'tweets' is not defined

In [ ]:
df = pd.